export default function Privacy(){
    return (
        <div className="privacy">
            <p>Kinetic Marketing Agency
Aviso de Privacidad | Términos y Condiciones.
Introducción
Esta Política de Privacidad describe las prácticas de Kinetic Marketing con respecto a la información recopilada de los usuarios que acceden a nuestro sitio web en: www.thekineticmarketing.com, o que de otro modo comparten información personal con nosotros.
¿Qué tipo de información recopilamos?
Recopilamos dos tipos de datos e información de los Usuarios. El primer tipo de información es información no identificada y no identificable perteneciente a un Usuario(s), que puede ponerse a disposición o recopilarse a través de su uso del Sitio ("Información no personal"). No conocemos la identidad de un Usuario del que se recopiló la Información no personal. La información no personal que se recopila puede incluir su información de uso agregada e información técnica transmitida por su dispositivo, incluida cierta información de software y hardware (por ejemplo, el tipo de navegador y sistema operativo que utiliza su dispositivo, idioma de preferencia, tiempo de acceso, etc.) con el fin de mejorar la funcionalidad de nuestro sitio. También podemos recopilar información sobre su actividad en el Sitio (por ejemplo, páginas vistas, navegación en línea, clics, acciones, etc.). El segundo tipo de información es Información personal, que es información que identifica a un individuo o puede identificar con un esfuerzo razonable individual. Dicha información pude incluir: Internet u otra información de actividad de red electrónica, que incluye principalmente información que recopilamos de su dispositivo, como: datos de geolocalización, dirección IP, identificadores únicos (por ejemplo, dirección MAC y UUID) y otra información relacionada con su actividad a través del Sitio. Identificadores: Información de registro: cuando se registre en nuestro Sitio, se le pedirá que nos brinde ciertos detalles como: nombre completo; correo electrónico o dirección física, y otra información. Esta información se recopila con el fin de proporcionar nuestro Servicio y para comunicarnos con usted. Los identificadores también incluyen cualquier información voluntaria que nos brinde cuando se comunica con nosotros (por ejemplo, cuando nos envía un correo electrónico o utiliza un formulario de "Contacto" en nuestro Sitio) recopilamos la información personal que nos proporcionó. Información comercial: si realiza o habilita una transacción como una compra directamente desde nuestro sitio, recopilaremos facturación e información financiera según sea necesario para procesar sus cargos, como el número de tarjeta de crédito, la dirección postal y de correo electrónico, datos de geolocalización, etc.
¿Con quién compartimos su información personal?
Retención
Retendremos su información personal durante el tiempo que sea necesario para proporcionar nuestros servicios y según sea necesario para cumplir con nuestras obligaciones legales, resolver disputas y hacer cumplir nuestras políticas. Los períodos de retención se determinarán teniendo en cuenta el tipo de información que se recopila y el propósito para el cual se recopila, teniendo en cuenta los requisitos aplicables a la situación y la necesidad de destruir la información desactualizada y no utilizada lo antes posible. Según las regulaciones aplicables, mantendremos registros que contengan datos personales del cliente, documentos de apertura de cuentas, comunicaciones y cualquier otra cosa que lo requieran las leyes y regulaciones aplicables.
Podemos rectificar, reponer o eliminar información incompleta o inexacta, en cualquier momento y a nuestra propia discreción.
Cookies
Nosotros y nuestros socios comerciales de confianza utilizamos cookies y otras tecnologías en nuestros servicios relacionados, incluso cuando visita nuestro Sitio o accede a nuestros servicios.
Una "cookie" es una pequeña información que un sitio web asigna a su dispositivo mientras está viendo un sitio web. Las cookies son muy útiles y se pueden usar para varios propósitos diferentes. Estos propósitos incluyen permitirle navegar entre páginas de manera eficiente, habilitar la activación automática de ciertas funciones, recordar sus preferencias y hacer que la interacción entre usted y nuestros Servicios sea más rápida y fácil. Las cookies también se utilizan para ayudar a garantizar que los anuncios que ve sean relevantes para usted y sus intereses, y para recopilar datos estadísticos sobre su uso de nuestros Servicios.
El sitio utiliza los siguientes tipos de cookies:
a. 'Cookies de sesión' que se almacenan solo temporalmente durante una sesión de navegación para permitir el uso normal del sistema y se eliminan de su dispositivo cuando se cierra el navegador;
b.'Cookies persistentes' que solo son leídas por el Sitio, guardadas en su computadora por un período fijo y no se eliminan cuando se cierra el navegador. Dichas cookies se usan cuando necesitamos saber quién es usted para visitas repetidas, por ejemplo, para permitirnos almacenar sus preferencias para el próximo inicio de sesión;
c.'Cookies de terceros' que son establecidas por otros servicios en línea que ejecutan contenido en la página que está viendo, por ejemplo, por compañías analíticas de terceros que monitorean y analizan nuestro acceso web.
Las cookies no contienen ninguna información que lo identifique personalmente, pero la información personal que almacenamos sobre usted puede estar vinculada, por nosotros, a la información almacenada y obtenida de las cookies. Puede eliminar las cookies siguiendo las instrucciones de las preferencias de su dispositivo; sin embargo, si elige deshabilitar las cookies, algunas características de nuestro sitio pueden no funcionar correctamente y su experiencia en línea puede ser limitada.
También utilizamos una herramienta llamada "Google Analytics" para recopilar información sobre su uso del Sitio. Google Analytics recopila información como la frecuencia con la que los usuarios acceden al Sitio, qué páginas visitan cuando lo hacen, etc. Utilizamos la información que obtenemos de Google Analytics solo para mejorar nuestro Sitio y nuestros servicios. Google Analytics recopila la dirección IP que se le asignó en la fecha en que visita los sitios, en lugar de su nombre u otra información de identificación. No combinamos la información recopilada mediante el uso de Google Analytics con información de identificación personal. La capacidad de Google para usar y compartir información recopilada por Google Analytics sobre sus visitas a este Sitio está restringida por los Términos de uso de Google Analytics y la Política de privacidad de Google.
La mayoría de los navegadores web aceptan automáticamente las cookies, pero le permiten modificar la configuración de seguridad para que pueda aprobar o rechazar las cookies caso por caso o rechazar todas las cookies. Puede configurar su navegador web para eliminar las cookies siguiendo las instrucciones proporcionadas en la sección de "Ayuda" de su navegador de Internet.
Safari, Opera, Firefox, Google chrome, Internet Explorer
Si está utilizando un dispositivo móvil, puede optar por no participar en ciertos tipos de publicidad basada en intereses accediendo a la "Configuración" en su dispositivo:
Si está utilizando un dispositivo Apple, puede configurar su dispositivo para limitar el seguimiento de anuncios haciendo clic en "Configuración"> "Privacidad"> "Publicidad" y alternando "Limitar el seguimiento de anuncios" a "Activado". Puede optar por la mayoría de los rastreos basados en aplicaciones para la publicidad abriendo la aplicación "Configuración de Google" en su dispositivo, seleccionando "Anuncios" y luego seleccionando la opción de cancelar la suscripción a los anuncios basados en intereses.
Tenga en cuenta que la información anterior puede cambiar cuando los fabricantes actualizan sus sistemas. También tenga en cuenta que su dispositivo puede usar otra plataforma, no descrita anteriormente. En ese caso, consulte la documentación del fabricante para obtener más instrucciones.
Recopilación de información por parte de terceros.
Nuestra política solo aborda el uso y divulgación de la información que recopilamos de usted. En la medida en que divulgue su información a otras partes o sitios a través de Internet, se pueden aplicar diferentes reglas a su uso o divulgación de la información que les divulga. En consecuencia, lo alentamos a leer los términos y condiciones y la política de privacidad de cada tercero al que elija revelar información.
Esta Política de privacidad no se aplica a las prácticas de las compañías que no poseemos o controlamos, ni a las personas que no empleamos ni administramos, incluidos los terceros a los que podemos divulgar información como se establece en esta Política de privacidad.
¿Cómo protegemos su información?
Tenemos mucho cuidado en implementar y mantener la seguridad del Sitio y su información. empleamos procedimientos y políticas estándar de la industria para garantizar la seguridad de la información que recopilamos y conservamos, y evitar el uso no autorizado de dicha información, y exigimos a cualquier tercero que cumpla con requisitos de seguridad similares , de acuerdo con esta Política de privacidad. Aunque tomamos medidas razonables para salvaguardar la información, no podemos ser responsables de los actos de aquellos que obtienen acceso no autorizado o abusan de nuestro Sitio, y no garantizamos, de manera expresa, implícita o de otro tipo, que impediremos dicho acceso.
Anuncios
Podemos utilizar una tecnología publicitaria de terceros para publicar anuncios cuando accede al Sitio. Esta tecnología utiliza su información con respecto a su uso de los Servicios para mostrarle publicidad (por ejemplo, colocando cookies de terceros en su navegador web).
Puede optar por no participar en muchas redes publicitarias de terceros, incluidas las operadas por miembros de Network Advertising Initiative ("NAI") y Digital Advertising Alliance ("DAA"). Para obtener más información sobre esta práctica por parte de los miembros de NAI y DAA, y sus opciones con respecto a que estas compañías usen esta información, incluida la opción de no participar en redes publicitarias de terceros operadas por miembros de NAI y DAA, visite sus respectivos sitios web: http : //optout.networkadvertising.org/#! / y http://optout.aboutads.info/#!/.
Otros recursos útiles: Para obtener más información sobre el uso de cookies por parte de los anunciantes, los siguientes enlaces pueden ser útiles:
Alianza Europea de Publicidad Digital Interactiva (UE) Oficina de Publicidad en Internet (EE. UU.) Oficina de Publicidad en Internet (UE)
Mercadeo
Podemos utilizar su información personal, como su nombre, dirección de correo electrónico, número de teléfono, etc. nosotros mismos o mediante el uso de nuestros subcontratistas externos con el fin de proporcionarle materiales promocionales, relacionados con nuestros servicios, que creemos que pueden interesarle.
Por respeto a su derecho a la privacidad, le proporcionamos dentro de dichos materiales de marketing medios para rechazar la recepción de nuevas ofertas de marketing de nuestra parte. Si cancela su suscripción, eliminaremos su dirección de correo electrónico o número de teléfono de nuestras listas de distribución de marketing.
Tenga en cuenta que incluso si se ha dado de baja de recibir correos electrónicos de marketing de nuestra parte, podemos enviarle otros tipos de comunicaciones importantes por correo electrónico sin ofrecerle la oportunidad de optar por no recibirlos. Estos pueden incluir anuncios de servicio al cliente o avisos administrativos.

Términos y condiciones de nuestros servicios
Términos y condiciones.
Generales.
El cliente al realizar el pago de su servicio acepta que ha leído los términos y condiciones, así como que está de acuerdo con ellos, de igual forma manifiesta que conoce nuestro aviso de privacidad.
Se reserva el derecho de contratación, excluyendo negocios relacionados con giros negros y todos aquellos que a nuestra discreción no se apeguen a los estándares internos para contratar nuestros servicios.
Horario de servicio. La atención a los clientes, así como de nuestros servicios se realizan en un horario de lunes a viernes de 9:00 a 18:00 horas (hora Buenos Aires, Argentina), las horas antes mencionadas son según el tipo de horario de la Ciudad de Buenos Aires, incluyendo sus cambios y variaciones. Exceptuando los días festivos señalados en el calendario oficial como días no laborables. 

Administración de redes.
El servicio tiene una duración de 30 días, los cuales comienzan el día que el cliente otorgue los datos, documentos y accesos solicitados por su community manager. 
Administración de redes sociales (Facebook, Instagram, Twitter, Pinterest, LinkedIn y/o Google My Business). Se realizarán las publicaciones de acuerdo al plan contratado, estos paquetes amparan una cantidad limitada de diseños, ofreciéndose de acuerdo al paquete 8, 12, 15 o 30 diseños al mes. Los diseños no son acumulables y una vez cumplido el lapso de los 30 días de servicio, no nos hacemos responsables en caso de no ser publicados en su totalidad. 
Proceso de trabajo: Una vez contratado el servicio se asignará a un equipo de community manager, diseñador y supervisor de cuenta, quienes le harán una entrevista al cliente para conocer sobre su negocio. Una vez realizada la entrevista se le solicitará al cliente envíe la información necesaria para preparar su parrilla de contenidos (texto, copy interno y externo), una vez recibida esta información se le hará la entrega al cliente su parrilla en un periodo de 2-3 días hábiles para su revisión y aprobación, en caso de existir algún cambio se procederá a realizar los cambios solicitados en los textos con un periodo de entrega de 1 día hábil posterior a la notificación de los cambios requeridos. Una vez aprobada la parrilla de textos se procederá a elaborar las imágenes y diseños, este proceso durará 5 días hábiles, al terminar los 5 días hábiles se le hará entrega al cliente de las imágenes para su revisión y podrá solicitar una sesión de cambios en las imágenes que considere que lo requiera, la entrega de estos cambios se hará en un periodo máximo de 2 días hábiles. Una vez aprobados los diseños se procederá a la publicación de las imágenes y programación del posteo de acuerdo a los días estipulados con el cliente dentro de un periodo de 30 días naturales.
Propuesta de segmentación. Se realizará sin costo adicional una propuesta al mes, en la cual no se incluye un monto a invertir. Todos los anuncios se realizarán desde el administrador de anuncios del cliente quien deberá brindarnos acceso a través de un rol.
Pago y reembolso.
El pago del servicio se realiza en una sola exhibición a través de los medios descritos en la página. 
Facturación. En caso de requerir factura de su compra, el cliente tendrá 30 días para solicitarla a partir de su fecha de compra. Y deberá de llenar previamente el formato solicitado con los datos correctos, Kinetic Marketing. no se hace responsable en caso de que algún dato sea erróneo, ya que es el cliente quien solicita dicho documento. 
Reembolsos. Se hará íntegro solo si el cliente lo solicita en las primeras 72 horas posteriores de haber realizado su pago. Y deberá presentar las evidencias necesarias, para demostrar el incumplimiento en los términos y condiciones adquiridos en Kinetic Marketing. una vez llegado el lapso establecido la devolución será improcedente. Este apartado puede ser modificado sin previo aviso, dando por entendiendo que una vez que el cliente adquiere el producto es aceptado. 
Cuando el pago se realice con un código promocional, no existirán reembolsos. El periodo de tiempo para que el reembolso se vea reflejado es de 7 a 15 días hábiles o lo que especifique la plataforma con la que realizó su pago, en este tipo de situaciones los casos quedan a consideración y validación del comité interno de Kinetic Marketing dando así el seguimiento correspondiente.
Pago anual. Al realizar el pago de manera anual, el reembolso solo aplicará 48 horas posteriores a su contratación. Una vez excedido dicho lapso de tiempo, se catalogará como improcedente la devolución de los fondos.
Pago manual. En este método de pago no se aplicarán reembolsos bajo ninguna circunstancia.
Al realizar la compra de cualquiera de nuestros servicios se da por entendido que el cliente conoce los términos y condiciones de nuestros servicios, y los acepta.
Creación de logos
Servicios
Creación de logo. Al contratar el servicio se enviará un cuestionario (BRIEF) en el cual nos basaremos para crear el diseño con las características solicitadas.
Propuestas. El diseñador desarrollará tres propuestas que se enviarán al cliente 5 días hábiles posteriores a su contratación. La propuesta adicional tendrá un costo de 25 usd.
Modificaciones. Las propuestas recibidas por el cliente se podrán modificar exclusivamente en cuanto a su tipografía, color y tamaño.
Entrega. Se realizará de forma digital en archivos PNG. JPG. SBG. AI., adjunto se entregará un manual corporativo y una paleta de colores. Incluye máximo 5 formatos: FAV-ICON, LANDSCAPE horizontal/vertical, logotipo y original. 
Pagos y reembolsos.
Pago. Se realizará en una sola exhibición a través de los medios digitales proporcionados en nuestro sitio web.
Reembolso. Para este servicio no aplicará reembolso bajo ninguna circunstancia.
Al realizar la compra de cualquiera de nuestros servicios se da por entendido que el cliente conoce los términos y condiciones de nuestros servicios, y los acepta.
Agencia de Marketing digital 
Al adquirir el cliente su membresía de agencia de marketing digital con Kinetic Marketing, la empresa se compromete a entregar el kit de agencia estipulado en sus paquetes y a ofrecer en tiempo y forma los servicios que vaya solicitando el cliente de acuerdo a la estipulación de cada uno de los paquetes y de los procesos internos que Kinetic Marketing manejen así como la privacidad de las cuentas publicitarias que se manejen para el lanzamiento de campañas serán exclusivamente responsabilidad de la gestión de la cuenta publicitaria propiedad de Kinetic Marketing, el cliente reconoce que si desea lanzar campañas publicitarias desde su cuenta personal deberá hacerlo exclusivamente por su propios medios, sin que se de acceso a Kinetic Marketing al manejo de las mismas, comprometiéndose Kinetic Marketing a la entrega de la propuesta acordada para evitar el conocimiento de información bancaria personal que pueda estar en las cuentas personales de los clientes.
Comprometiéndose de igual forma a actuar como marca blanca sin revelar en ningún momento a los clientes de la agencia contratada su identidad u ofrecer ningún tipo de promoción de manera directa sin que el propietario de la agencia este de común acuerdo.
Las membresías de agencia constan de un pago único sin ser una anualidad fija, por tal motivo el cliente deberá respetar los procesos internos de la empresa y en caso de requerir servicios especiales deberá solicitar cotizaciones de acuerdo a las posibilidades de atención de Kinetic Marketing. De igual manera queda estrictamente prohibido que el representante de agencia, o algún miembro del equipo de la agencia del cliente, ofrezca trabajo o realización de algún proyecto a cualquiera de los colaboradores de Kinetic Marketing, de manera directa y por fuera de la empresa. Todos nuestros colaboradores cuentan con un contrato de confidencialidad, y al presentarse una situación de esta índole, están obligados a reportarlo a su superior. Si alguna de estas situaciones se llegará a presentar se suspenderá de manera definitiva e inmediata la membresía contratada sin reembolso alguno y la agencia no podrá adquirir ningún servicio adicional con Kinetic Marketing.
La agencia de marketing esta enterada que en todo momento la comunicación deberá ser entre el representante de la agencia y el coordinador asignado por social conecta para la atención de cualquiera de los servicios ofrecidos por la empresa los cuales se ofrecerán a través de la agencia final al cliente siendo social conecta un prestador de servicios y guardara en todo momento la confidencialidad de los datos del cliente de la agencia en cuestión.
Pagos y reembolsos.
Pago. Se realizará en una sola exhibición a través de los medios digitales proporcionados en nuestro sitio web.
Reembolso. Para este servicio no aplicará reembolso bajo ninguna circunstancia.
Al realizar la compra de cualquiera de nuestros servicios se da por entendido que el cliente conoce los términos y condiciones de nuestros servicios, y los acepta.
Creación de Sitios Web
Paquetes de desarrollo de sitio web
El desarrollo del sitio web se realiza en un CMS interno basado en los lenguajes de programación HTML, JavaScript y CSS, con un alojamiento de la plataforma en Dattatec (DonWeb) la creación del sitio estará basada en la matriz de características estipuladas en nuestro sitio web y cualquier programación que se requiera adicional deberá solicitarse previa cotización. El sitio web puede ser pagado de dos maneras en modo mensual o en modo anual.
Sitios web informativo modo mensual: Se realizará un pago inicial estipulado en nuestro sitio de acuerdo al tipo de sitio web que elija el cliente, este pago inicial ya incluye la primera mensualidad del servicio y deberá concretar una totalidad de 11 mensualidades adicionales para terminar el pago del servicio. En caso de no realizar el pago de alguna de las mensualidades se suspenderá el servicio y el sitio web aparecerá como sitio no disponible hasta que el cliente realice su pago, en caso de tener más de dos meses seguidos sin realizar el pago se procederá a la eliminación del sitio de manera permanente. Posterior a los 11 meses de servicio el cliente puede elegir renovar el hosting con nuestra plataforma por un valor de 125 usd por un año adicional o puede elegir que su sitio se exporte en un archivo html para que el cliente decida cargarlo en otro hosting. 
Nota: El proceso de carga del archivo exportado no está incluido en nuestros servicios el cliente deberá tener los conocimientos para la carga de su sitio en un nuevo hosting o contratar a un profesional externo a Kinetic Marketing para poder vincular el código a su sitio, el cliente debe considerar que algunas funciones que estaban dentro de nuestra plataforma no estarán disponibles en el nuevo servidor)
Sitios web informativo modo anual: Se realiza el pago en una sola exhibición en nuestro sitio de acuerdo al tipo de sitio web que elija el cliente, Posterior a los 11 meses de servicio el cliente puede elegir renovar el hosting con nuestra plataforma por un valor de 125 usd por un año adicional o puede elegir que su sitio se exporte en un archivo html para que el cliente decida cargarlo en otro hosting. 
Nota: El proceso de carga del archivo exportado no está incluido en nuestros servicios el cliente deberá tener los conocimientos para la carga de su sitio en un nuevo hosting o contratar a un profesional externo a Kinetic Marketing para poder vincular el código a su sitio, el cliente debe considerar que algunas funciones que estaban dentro de nuestra plataforma no estarán disponibles en el nuevo servidor)
Tiendas en línea: La tienda en línea se realizará con la vinculación directa de la plataforma de WordPress (WooCommerce) en hosting de dattatec (DonWeb), una vez realizada la compra, se dará acceso a un panel administrativo basado en las funciones que explica nuestra matriz de características dentro de nuestro sitio, el costo de renovación del hosting de nuestras tiendas en línea aplica el valor de 125 usd del sitio más el pago de uso de la tienda que será de acuerdo al paquete contratado. Tienda básica 75 usd, tienda completa 225 usd, tienda ilimitada 500 usd. En caso de que el cliente no desee continuar con el servicio de tienda puede elegir que su sitio se exporte en un archivo html para que el cliente decida cargarlo en otro hosting. 
Nota: El proceso de carga del archivo exportado no está incluido en nuestros servicios el cliente deberá tener los conocimientos para la carga de su sitio en un nuevo hosting o contratar a un profesional externo a Kinetic Marketing para poder vincular el código a su sitio, el cliente debe considerar que algunas funciones que estaban dentro de nuestra plataforma no estarán disponibles en el nuevo servidor)
Los Servicios, incluidos, entre otros, el procesamiento de pagos, pueden ser manejados directamente por Nosotros o por terceros en línea. Cuando un tercero maneja un pago, el pago está sujeto a los términos de uso y la política de privacidad de dicho tercero (incluidos, entre otros, métodos de pago, responsabilidad fiscal, recopilación y uso de sus datos personales y niveles de soporte). Le recomendamos que revise los términos de uso y la política de privacidad de dichos terceros antes de enviar sus Datos personales y utilizar los servicios de dichos terceros.
Traducción. Cuando utilice nuestra función multilingüe, tendrá la opción de traducir el Contenido existente del sitio web mediante Google Translate. Google desea que tenga en cuenta el siguiente descargo de responsabilidad:
"ESTE SERVICIO PUEDE CONTENER TRADUCCIONES IMPULSADAS POR GOOGLE. GOOGLE RECHAZA TODAS LAS GARANTÍAS RELACIONADAS CON LAS TRADUCCIONES, EXPRESAS O IMPLÍCITAS, INCLUIDAS LAS GARANTÍAS DE EXACTITUD, CONFIABILIDAD Y CUALQUIER GARANTÍA IMPLÍCITA DE COMERCIABILIDAD, IDONEIDAD PARA UNA PURPURACIÓN PARTICULAR".
No somos propietarios ni reclamamos la propiedad del contenido enviado para su inclusión o visualización en tu sitio web, sitio web para celulares o para su inclusión/visualización en cualquier otro servicio (entre tú y nosotros, "tu contenido"). Tu contenido incluye, entre otras cosas: información, datos, texto, software, música, sonido, fotografías, gráficos, videos, mensajes, bienes, productos, servicios u otros materiales incluidos en cualquier sitio que alojes a través del servicio. Eres responsable de todo tu contenido que se suba, publique, transmita o ponga a disposición de cualquier otra forma a través de nuestros servicios. No controlamos tu contenido o cualquier contenido que publiques a través de nuestros servicios y eres responsable de cualquier contenido que pueda perderse o ser irrecuperable a través del uso de los servicios. Eres responsable de archivar y hacer una copia de seguridad de tu contenido de manera regular y frecuente.
PRIVACIDAD Y PROTECCIÓN DE DATOS
Para los propósitos de este Acuerdo:
"Visitante del sitio" significa su usuario final, como un visitante de su sitio.
"Datos del visitante del sitio" se refiere a todos y cada uno de los datos y contenidos de un visitante del sitio, incluidos, entre otros, palabras, música, imágenes y videos.
Por "Leyes de protección de datos" se entenderán todas las leyes, reglamentos u ordenanzas nacionales, extranjeros, estatales o locales, u otras normas gubernamentales relativas a la privacidad, la confidencialidad o la seguridad de los datos personales, incluidas, entre otras, la Directiva 2002/58/CE sobre comunicaciones electrónicas (y las respectivas leyes locales de aplicación, junto con la legislación nacional de aplicación pertinente), el Reglamento general de protección de datos de la UE (2016/679) ("RGPD") y la Ley de protección de la intimidad de los consumidores de California de 2018 (a partir de la sección 1798.100 del Código Civil de California) y cualquier reglamento promulgado en virtud de la misma (el "CCPA").
Pagos y reembolsos.
Pago. Se realizará en una sola exhibición a través de los medios digitales proporcionados en nuestro sitio web.
Reembolso. Para este servicio no aplicará reembolso bajo ninguna circunstancia.
Al realizar la compra de cualquiera de nuestros servicios se da por entendido que el cliente conoce los términos y condiciones de nuestros servicios, y los acepta.
Ninguna renuncia a ningún término de este Acuerdo se considerará una renuncia adicional o continua de dicho término o de cualquier otro término, y cualquier incumplimiento de cualquier derecho o disposición en virtud del Acuerdo no constituirá una renuncia a dicho término. Usted no puede transferir ni ceder este Acuerdo ni los derechos y licencias otorgados en virtud del presente, pero nosotros podemos cederlos sin restricciones. Usted acepta que no existe una relación de empresa conjunta, sociedad, empleo, franquicia o agencia entre Usted y Nosotros como resultado del uso del Sitio o los Servicios. Este Acuerdo comprende el acuerdo completo entre Usted y Nosotros, establece la responsabilidad total de Nuestros y Nuestros proveedores y Su remedio exclusivo con respecto al Sitio y los Servicios, y reemplaza todos los acuerdos anteriores relacionados con el tema del mismo. Si se considera que alguna disposición de este Acuerdo es contraria a la ley, dicha disposición se interpretará, en la medida de lo posible, para reflejar la disposición original y las demás disposiciones permanecerán en pleno vigor y efecto. Los títulos de las secciones en este Acuerdo se utilizan únicamente para la conveniencia y no tienen importancia legal o contractual. Ninguna disposición del Acuerdo se interpretará en contra de Nosotros, sino que se interpretará de manera neutral y justa como términos suscritos por una parte totalmente informada de forma voluntaria después de la oportunidad de consultar con asesores y asesores legales sobre el significado y los efectos de los términos de este Acuerdo.
Videomarketing
Creación de videos. Al contratar el servicio se enviará un cuestionario (BRIEF) en el cual nos basaremos para crear el video con las características solicitadas.
Propuestas. El videomaker desarrollará el video que se enviarán al cliente de 5 a 7 días hábiles posteriores a su contratación y a recibir la información solicitada por el videomaker. La propuesta adicional tendrá un costo de $25 usd.
Modificaciones. Las propuestas recibidas por el cliente se podrán modificar exclusivamente en cuanto a su tipografía, color y tamaño.
Entrega. Se realizará de forma digital en archivos PNG. JPG. SBG. AI., adjunto se entregará un manual corporativo y una paleta de colores. Incluye máximo 5 formatos: FAV-ICON, LANDSCAPE horizontal/vertical, logotipo y original.
Pagos y reembolsos.
Pago. Se realizará en una sola exhibición a través de los medios digitales proporcionados en nuestro sitio web.
Reembolso. Para este servicio no aplicará reembolso bajo ninguna circunstancia.
Al realizar la compra de cualquiera de nuestros servicios se da por entendido que el cliente conoce los términos y condiciones de nuestros servicios, y los acepta.
Campañas de Google ADS y Facebook ADS
El costo de nuestros servicios de campañas de Facebook o Google Ads incluyen una propuesta de segmentación, en la cual no se incluye un monto a invertir. Todos los anuncios se realizarán desde el administrador de anuncios del cliente, quién deberá brindarnos acceso a través de un rol. Las propuestas de campaña incluyen el servicio de segmentación del público objetivo, Kinetic Marketing no garantiza resultados en las campañas, el alcance de cada una de las propuestas está basada en una determinación de las mismas plataformas de Facebook o Google de acuerdo a los comportamientos, datos demográficos e intereses de cada uno de los públicos creados así como de las palabras clave, el servicio incluye el lanzamiento y monitoreo de la campaña por un coordinador de campañas quien dará una supervisión en un horario de 09:00 a 18:00 hora Ciudad de Buenos Aires, de lunes a viernes en los días hábiles que estipule la ley.
Pagos y reembolsos.
Pago. Se realizará en una sola exhibición a través de los medios digitales proporcionados en nuestro sitio web.
Reembolso. Para este servicio no aplicará reembolso bajo ninguna circunstancia.
Al realizar la compra de cualquiera de nuestros servicios se da por entendido que el cliente conoce los términos y condiciones de nuestros servicios, y los acepta.
Menores
Entendemos la importancia de proteger la privacidad de los niños, especialmente en un entorno en línea. El sitio no está diseñado ni dirigido a niños. Bajo ninguna circunstancia permitiremos el uso de nuestros servicios por parte de menores sin el consentimiento previo o la autorización de un padre o tutor legal. No recopilamos intencionalmente información personal de menores. Si un padre o tutor se da cuenta de que su hijo nos ha proporcionado información personal sin su consentimiento, debe comunicarse con nosotros al siguiente correo electrónico info@thekineticmarketing.com
Actualizaciones o enmiendas a esta Política de privacidad
Nos reservamos el derecho de modificar o revisar periódicamente la Política de privacidad; los cambios materiales entrarán en vigencia inmediatamente después de que se muestre la Política de privacidad revisada. La última revisión se reflejará en la sección "Última modificación". Su uso continuo de la Plataforma, luego de la notificación de dichas modificaciones en nuestro sitio web, constituye su reconocimiento y consentimiento de dichas modificaciones a la Política de privacidad y su aceptación de estar sujeto a los términos de dichas modificaciones. [Requerido bajo CCPA] Sin perjuicio de lo anterior, a partir del 1 de enero de 2020, esta Política se actualizará al menos una vez cada 12 meses y nos reservados los derechos de dar previos avisos o notificaciones a nuestros clientes sobre dichos cambios.
Cómo contactarnos
Si tiene alguna pregunta general sobre el Sitio o la información que recopilamos sobre usted y cómo la usamos, puede contactarnos en el siguiente correo electrónico info@thekineticmarketing.com.

 

 

Última modificación Mayo 2022</p>

        </div>
    )
}